const countriesArray = [
	{
		id: 0,
		country: 'Serbia',
		img: 'serbia.png',
		cities: ['Belgrade'],
	},
	{
		id: 1,
		country: 'Australia',
		img: 'australia.png',
		cities: ['Sydney', 'Perth', 'Brisbane', 'Melbourne', 'Adelaide'],
	},
	{
		id: 2,
		country: 'China',
		img: 'china.png',
		cities: [
			'Beijing',
			'Macau',
			'Shanghai',
			'Chongqing',
			'Tianjin',
			'Anqing',
			'Bengbu',
			'Bozhou',
			'Chaohu',
			'Huaibei',
			'Huangshan',
			'Wuhu',
			'Dingxi',
		],
	},
	{
		id: 3,
		country: 'Russia',
		img: 'russia.png',
		cities: [
			'Moscow',
			'Saint Petersburg',
			'Kazan',
			'Novosibirsk',
			'Yekaterinburg',
			'Kazan',
			'Nizhny Novgorod',
			'Samara',
		],
	},
	{
		id: 4,
		country: 'UK',
		img: 'uk.png',
		cities: [
			'London',
			'Manchester',
			'Birmingham',
			'Bristol',
			'Cambridge',
			'Canterbury',
			'Cardiff',
			'Chester',
			'Derby',
		],
	},
	{
		id: 5,
		country: 'USA',
		img: 'usa.png',
		cities: [
			'New York',
			'Los Angeles',
			'Chicago',
			'Phoenix',
			'Dallas',
			'Washington',
			'Boston',
			'Oklahoma City',
		],
	},
	{
		id: 6,
		country: 'Germany',
		img: 'germany.png',
		cities: [
			'Berlin',
			'Hamburg',
			'Munich',
			'Cologne',
			'Stuttgart',
			'Düsseldorf',
			'Dortmund',
			'Remscheid',
			'Kaiserslautern',
		],
	},
	{
		id: 7,
		country: 'France',
		img: 'france.png',
		cities: [
			'Paris',
			'Marseille',
			'Lyon',
			'Lille',
			'Strasbourg',
			'Nantes',
			'Toulouse',
			'Le Havre',
			'Dijon',
		],
	},
];

export default countriesArray;
