export const FETCH_WEATHERAPI_REQUEST = 'FETCH_WEATHERAPI_REQUEST';
export const FETCH_WEATHERAPI_SUCCESS = 'FETCH_WEATHERAPI_SUCCESS';
export const FETCH_WEATHERAPI_FAILURE = 'FETCH_WEATHERAPI_FAILURE';

export const GET_COUNTRY = 'GET_COUNTRY';
